version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm run test
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes
